/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabajolab5.Interfaz;

import java.util.ArrayList;
import java.util.List;



/**
 *
 * @author Emiliano
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

   
    
    public frmMenuPrincipal() {
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        itemBuscarCliente = new javax.swing.JMenuItem();
        btnBorrarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemBuscarPorCiudad = new javax.swing.JMenuItem();
        itemBuscarTelefono = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemCiudad = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 102, 204));
        escritorio.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jMenu1.setText("Clientes");

        itemCliente.setText("Agregar Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        jMenu1.add(itemCliente);

        itemBuscarCliente.setText("Buscar Cliente");
        itemBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(itemBuscarCliente);

        btnBorrarCliente.setText("Borrar Cliente");
        btnBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(btnBorrarCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Directorio");

        itemBuscarPorCiudad.setText("Buscar Cliente por Ciudad");
        itemBuscarPorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarPorCiudadActionPerformed(evt);
            }
        });
        jMenu2.add(itemBuscarPorCiudad);

        itemBuscarTelefono.setText("Buscar Telefono por Apellido");
        itemBuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarTelefonoActionPerformed(evt);
            }
        });
        jMenu2.add(itemBuscarTelefono);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Ciudad");

        itemCiudad.setText("Agregar Ciudad");
        itemCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCiudadActionPerformed(evt);
            }
        });
        jMenu6.add(itemCiudad);

        jMenuBar1.add(jMenu6);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        Salir.add(itemSalir);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmAgregarCliente cliente=new frmAgregarCliente();
        cliente.setVisible(true);
        escritorio.add(cliente);
        escritorio.moveToFront(cliente);
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCiudadActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmAgregarCiudad ciudad=new frmAgregarCiudad();
        ciudad.setVisible(true);
        escritorio.add(ciudad);
        escritorio.moveToFront(ciudad);    }//GEN-LAST:event_itemCiudadActionPerformed

    private void itemBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmBuscar b1=new frmBuscar();
        b1.setVisible(true);
        escritorio.add(b1);
        escritorio.moveToFront(b1);    
    }//GEN-LAST:event_itemBuscarClienteActionPerformed

    private void btnBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmBorrar borrar=new frmBorrar();
        borrar.setVisible(true);
        escritorio.add(borrar);
        escritorio.moveToFront(borrar);
    }//GEN-LAST:event_btnBorrarClienteActionPerformed

    private void itemBuscarPorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarPorCiudadActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmBuscarClienteCiudad buscarCiudad=new frmBuscarClienteCiudad();
        escritorio.add(buscarCiudad);
         buscarCiudad.setVisible(true);
        escritorio.moveToFront(buscarCiudad);
       
    }//GEN-LAST:event_itemBuscarPorCiudadActionPerformed

    private void itemBuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarTelefonoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        frmBuscarTelefonoPorApellido buscarApellido=new frmBuscarTelefonoPorApellido();
        buscarApellido.setVisible(true);
        escritorio.add(buscarApellido);
        escritorio.moveToFront(buscarApellido);
    }//GEN-LAST:event_itemBuscarTelefonoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Salir;
    private javax.swing.JMenuItem btnBorrarCliente;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemBuscarCliente;
    private javax.swing.JMenuItem itemBuscarPorCiudad;
    private javax.swing.JMenuItem itemBuscarTelefono;
    private javax.swing.JMenuItem itemCiudad;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
